language: python
sudo: required
os: linux
dist: trusty
python:
  - "2.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y swig
  - git clone https://github.com/pmatigakis/jsbsim.git
  - cd jsbsim
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=true ..
  - make
  - sudo make install
  - sudo ldconfig
  - cd ../..
  - git clone https://github.com/pmatigakis/PyJSBSim.git
  - cd PyJSBSim
  - python setup.py build_ext install
  - cd ..
install:
  - python setup.py install
before_script:
  - pip install robotframework
  - pip install robotframework-requests
  - pip install flake8
script:
  - python setup.py nosetests --with-coverage --cover-xml
  - cd robot
  - pybot aircraft_api.robot simulator_control.robot fdm.robot frontend.robot fdm_initial_condition.robot waypoints.robot simulator_reset_condition.robot
  - cd ..
  - flake8 huginn
after_success:
  - bash <(curl -s https://codecov.io/bash)
